# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/humble-database',
                'doc_host': 'https://schlinkertc.github.io',
                'git_url': 'https://github.com/schlinkertc/humble-database',
                'lib_path': 'humble_database'},
  'syms': {'humble_database.core': {'humble_database.core.foo': ('core.html#foo', 'humble_database/core.py')}}}
